services:
  influxdb:
    image: influxdb:1.8
    ports:
     - "8086:8086"
    networks:
     - mon1-network
    volumes:
     - ./influxdb/influx_init.iql:/docker-entrypoint-initdb.d/influx_init.iql
     - ./influxdb/data:/var/lib/influxdb

  grafana:
    image: grafana/grafana-oss:latest
    depends_on:
      - influxdb
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    env_file:
      - 'grafana.env'
    networks:
      - mon1-network

networks:
  mon1-network:
    driver: bridge
